import type { Metadata } from "next";
import { Inter , Roboto , Sriracha} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"] , display: 'swap', weight: '400'});
const sriacha = Sriracha({ subsets: ["latin"] , display: 'swap', weight: '400'});


export const metadata: Metadata = {
  title: "Happy Birth Day Mint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sriacha.className}>{children}</body>
    </html>
  );
}
